version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        depends_on:
          - php
        links:
          - php
    php:
        build: .
        volumes:
            - ./code:/code
        networks:
            - code-network
        depends_on:
          - mysql
        links:
          - mysql
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
        ports:
            - "3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"

networks:
    code-network:
        driver: bridge
